### PR TITLE
feat(graphql) Add eslint-plugin-graphql (fixes noref)

### PR DESCRIPTION
**Pull request by pcgilday**

### CODE REVIEW

**Comment by pcgilday** [comment]
*[a discussion](https://reviewable.io:443/reviews/homezen/eslint-config-homezen/74#-L47mDgUnyUl17uVd7xy:-L47mDgUnyUl17uVd7xz:b-ywcjax) (no related file):*
Is this all that is needed to add a new plugin here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/eslint-config-homezen/74)*

**Comment by pcgilday** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/eslint-config-homezen/74)*

**Comment by SpainTrain** [comment]
*[graphql.js, line 3 at r1](https://reviewable.io:443/reviews/homezen/eslint-config-homezen/74#-L47li6hMnLml8T3-3SX:-L47li6hMnLml8T3-3SY:b-bag11w) ([raw file](https://github.com/homezen/eslint-config-homezen/blob/da5428923b1d3c4047e20d05cfa9a9aa2dd868eb/graphql.js#L3)):*
> ```JavaScript
> 'use strict'
> 
> module.exports = {
> ```

To be more useful, I think this should set a rule that is a sensible default.  Since we are using literal files I'd think https://github.com/apollographql/eslint-plugin-graphql#example-config-when-using-graphqlconfig assuming use of `.graphqlconfig` is a good default.

maybe also Capitalized Types https://github.com/apollographql/eslint-plugin-graphql#capitalization-of-a-first-letter-of-a-type-name

maybe also Named Operations https://github.com/apollographql/eslint-plugin-graphql#named-operations-validation-rule

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/eslint-config-homezen/74)*

**Comment by SpainTrain** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/eslint-config-homezen/74)*

**Comment by SpainTrain** [comment]
:shipit:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/eslint-config-homezen/74#-:-L48El9KJ7vfjNlj8nfK:b-xr9eiq)*

**Pull request merged**
