### PR TITLE
:gift_heart: Added flowtype config (fixes noref)

### PR DESCRIPTION
**Pull request by SpainTrain**
- Added config for flowtype plugin
- Added yarn.lock

### CODE REVIEW

**Comment by SpainTrain** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/eslint-config-homezen/46)*

**Comment by SpainTrain** [comment]
*[a discussion](https://reviewable.io:443/reviews/homezen/eslint-config-homezen/46#-KpWdcqJZ2ghGrrP-NvT:-KpWdcqKfTvPbagbX-UC:bed9tvv) (no related file):*
FYI

https://stackoverflow.com/a/45120231/278891

https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype-configuration

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/eslint-config-homezen/46)*

**Comment by pcgilday** [comment]
:shipit:

---

Reviewed 2 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/eslint-config-homezen/46#-:-KpWiwuTD_FRRmzVjNrH:b-xr9eiq)*

**Comment by pcgilday** [comment]
Reviewed 3 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/eslint-config-homezen/46)*

**Pull request merged**
