### PR TITLE
:gift_heart: ES Modules - check circular deps (fixes noref)

### PR DESCRIPTION
**Pull request by SpainTrain**
- Check for circular deps in es-modules config
- Added optional dep of webpack to squelch peer dep warnings in
  consuming projects

release v+minor

---
This change is [Reviewable](https://reviewable.io/reviews/homezen/eslint-config-homezen/8)

### CODE REVIEW

**Comment by pcgilday** [comment]
:shipit:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/eslint-config-homezen/8#-:-KeZlw9uCrt9zyVTO6-q:b-xr9eiq)*

**Comment by SpainTrain** [comment]
This is not so straightforward, see https://github.com/homezen/hz-webapp/pull/2847

**Comment by SpainTrain** [comment]
> This is not so straightforward, see homezen/hz-webapp#2847

of course it can be disabled manually in that one project, it's worth considering generally if we are ok with benign circular deps (certain kinds of circular deps are indeed allowed/supported by the es modules spec).

**Comment by pcgilday** [comment]
Yeah, I think I would prefer to have this for most modules, and then override in webapp to show warnings (or disable and rely on plugin you added) so that we are aware of benign ones. However, I would be alright leaving it out and just using the madge plugin to see where they are. 

Having either this or the madge script would have saved me a ton of time last night as it wasn't immediately clear what was wrong. 

While I would prefer to avoid even benign ones (and some of the webapp benign ones appear quick to fix), I could see the argument of "if they are benign why would we spend time reorganizing", so I could go either way as long as there is an obvious way to track these down in projects.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/eslint-config-homezen/8#-:-KeZqGYPZROUvepaUD9y:b-o5o0pc)*

**Pull request merged**
